run:
	g++ -Wall -shared -fPIC -o mymodule.so mymodule.cpp -lboost_python38 -I/usr/include/python3.8
	

help:
	@echo "https://www.boost.org/doc/libs/1_46_1/libs/python/doc/tutorial/doc/html/index.html"
