run:
	g++ -Wall -shared -fPIC -o overload.so overload.cpp -lboost_python38 -lpython3.8 -I/usr/include/python3.8
	

help:
	@echo "https://www.boost.org/doc/libs/1_46_1/libs/python/doc/tutorial/doc/html/index.html"
	@echo "https://skebanga.github.io/embedded-python/"
